### ISSUE TITLE
Task: Re-design chat box

### ISSUE THREAD

**Issue by ReinderVosDeWael** [childmindresearch/agate#14]
### Description

The chat box isn't exactly pretty.

### Tasks

- [x] Move end chat down to bottom of page.
- [x] Keep the system prompt as the first message in the chat box. 
- [x] Messages from you go on right, have different color (see Whatsapp interface).

**Comment by ReinderVosDeWael** [comment]
Resolved by #23
