### ISSUE TITLE
Task: Modularize the CMI Theme

### ISSUE THREAD

**Issue by ReinderVosDeWael** [childmindresearch/agate#15]
### Description

The CMI theme is currently part of this repository, but should be on its own repo and installable via npm.

### Tasks

- [ ] Finalize the CMI theme. 
- [x] Create a repository and npm package for the CMI theme
- [ ] Add npm theme to this repository.
