### ISSUE TITLE
Task: Add a local memory of chats

### ISSUE THREAD

**Issue by ReinderVosDeWael** [childmindresearch/agate#74]
### Description

I often find myself defaulting to ChatGPT because of its chat memory. I don't want to store chats server-side due to the potential of protected data being stored in them, but local storage would have no such restrictions. 

### Tasks

- [ ] Implement local storage of chats.
  - [ ] Stores all messages
  - [ ] Stores the model used
- [ ] Allow the user to easily switch between old chats.
