### ISSUE TITLE
Task: Add diarization to transcription

### ISSUE THREAD

**Issue by ReinderVosDeWael** [childmindresearch/agate#80]
### Description

Diarization of transcripts is a recurring need across CMI operations. The goal of this task is to integrate [Azure's diarization](https://learn.microsoft.com/en-us/azure/ai-services/speech-service/get-started-stt-diarization?tabs=linux&pivots=programming-language-javascript) into Agate.  

### Tasks

- [ ] Add a diarization option to the transcription page.
- [ ] If diarization is checked, send the transcription to Azure AI services, rather than Azure OpenAI.
- [ ] Add an explanation that different models are used depending on whether or not diarization is requested.
